version: '3.7'
services:
  todo-backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: todo-backend
    depends_on:
      - todo-db
    environment:
      - DB_URL=${DB_CONNECT_STRING}
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
      - '6969:6969'
    volumes:
      - .:/app
      - node_modules:/app/node_modules

  todo-db:
    container_name: todo-db
    environment:
      - POSTGRES_USER=${DB_USER}t
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    image: postgres:11
    ports:
      - 0.0.0.0:{DB_PORT}:5432
