version: '3.7'
services:
  todo-backend:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - todo-db
    container_name: todo-backend
    env_file:
      - .env
    environment:
      - DB_URL=${DB_CONNECT_STRING}
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
      - '9229:9229' # Port for debug
    volumes:
      - .:/app
      - /app/node_modules # Anonymous volume
    networks:
      - webnet

  todo-db:
    image: postgres:11-alpine
    container_name: todo-db
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      PG_DATA: /var/lib/postgresql/data
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 0.0.0.0:${DB_PORT}:5432
    networks:
      - webnet

networks:
  webnet:
volumes:
  pgdata:
