version: 1

update_configs:
  - package_manager: 'javascript'
    directory: '/'
    update_schedule: 'monthly'
    automerged_updates:
      - match:
          dependency_type: 'development'
          update_type: 'all'
    default_labels:
      - 'dependencies'
      - 'dependabot'
    default_assignees:
      - 'quangnv281098'
    commit_message:
      prefix: 'fix'
      prefix_development: 'chore'
      include_scope: true
